### PR TITLE
optimized some classes

### PR DESCRIPTION
**Pull request by Snabeldier**
I have optimized some classes, made the code a bit more performance-optimized and cleaned up the code according to Java conventions

### CODE REVIEW

**Comment by bergerkiller** [comment]
I disagree with a lot of these changes. Its not an optimization to remove {} braces. I keep those in on purpose because leaving those out has a serious risk of introducing bugs when copying code around. There's also a lot of needless changes like removing spaces and stuff.

I ask: why?

**Comment by bergerkiller** [comment]
ScreenShot 2022-07-09 17 39 30
stuff like this is unacceptable. Sorry if these code standards weren't clear before.

**Comment by bergerkiller** [comment]
I'm seriously confused what made you believe that removing {} around every single for loop and if statement is improving anything at all "according to java conventions". It changes nothing about performance and in many style checkers is explicitly disallowed.

It seems to me you used your IDE to automate this process because I can pick out numerous cases where this caused really dodgy code to be generated that violates a number of rules.

A few things can be useful improvements, like replacing if-else with a terniary ?, but it will have no real performance impact.

If you can get rid of all these mass-scale style changes and include only those changes that have an actual measureable change in performance, I can take another look.

**Comment by bergerkiller** [comment]
Some stuff I'm fine with, like this https://github.com/bergerhealer/TrainCarts/pull/448/commits/2eb41cb7991c1b22b2e9a79ee902510f8a41d135

But its just covered in a large-scale reformatting operation full of dangerous things like if (statement) try {

**Comment by Snabeldier** [comment]
I understand your point about the {} brackets. I will check my changes for their meaning and if necessary create another pull request in the future. Have a nice day!

**Pull request closed without merging**
