### PR TITLE
1.9

### PR DESCRIPTION
**Pull request by Clarkcj12**

### CODE REVIEW

**Comment by mg-1999** [comment]
Does it work?

**Comment by harm27** [comment]
Does not look that this has more changes that did you make yourself @mg-1999. I guess he just wants that into the master branch.

**Comment by mg-1999** [comment]
@harm27 the master branch is for stable releases only. And the 1.9 branch is still in development.

**Comment by harm27** [comment]
Yep, that is what i would expect. Maybe @Clarkcj12 doesn't know. Or guesses that 1.9 is stable. Since officially bukkit and spigot already on 1.11.2.

**Pull request closed without merging**
