### PR TITLE
Change/update issue templates

### LINKED ISSUE #287: Request: Update GitHub Issue Templates to using updated Templates
The current legacy issue templates should be updated to using the newer issue templates GitHub has to offer.
See the following for more info:
https://help.github.com/en/articles/creating-issue-templates-for-your-repository

(Same for the rest of the repositories, thanks!)

### PR DESCRIPTION
**Pull request by Andre601**
Closes #287 

This PR updates the current issue templates, by moving them into a `ISSUE_TEMPLATE` folder and also adding a feature request template to it.
In addition was also a config.yml added, which allows customisation (to a certain extend) of the Template chooser.

The config contains the current settings:

- Allow choosing blank issue (Skipping any template): True
- Link to Spigot page
- Link to Jenkins page (Direct link to TrainCarts Job)

I also wanted to add the Javadoc link, but this one seems to be quite unstable (Currently unavailable).
Please let me know if any additional information should be added, or if any of the above settings should be changed.

(I also would like to point out, that the issue templates allow for automatic setting/adding of labels, assignees and pre-set titles)

### CODE REVIEW

**Comment by bbayu123** [comment]
... I don't know about this... I know for a fact that things will break if this is done without changing other stuff...

**Comment by weeryan17** [comment]
What? this breaks literally nothing, its just improving issue templates.

**Comment by bbayu123** [comment]
Yea, I can see you don't ever use the /train issue command, just fix that and that will be good, that command auto-fills the page with the versions.

**Comment by bbayu123** [comment]
Actually, I'm only assuming it will be broken, as I cannot prove otherwise.

**Comment by weeryan17** [comment]
This doesn't break that. The issue command puts the data in the url. it doesn't use the current issue template as stored on github, although the command should be updated to reflect the new template, or requests the template from github.

**Comment by bbayu123** [comment]
Well, I guess... change that then, for sake of consistency.

**Comment by Andre601** [comment]
I personally see absolutely no benefit of having a dedicated command that pre-fills a issue with info, since the templates do exist for valid reasons and this would only make it much more annoying.

I suggest to - at most - update the command to just provide the link to the bug report template and perhaps also mention the required info (plugin and server version) for them to fill in.

**Comment by bergerkiller** [comment]
Rather than suggesting to use /version BKCommonlib and /version Traincarts, people should use /train version to get both versions at once. And more importantly, it gives me the build number, /version doesn't do that. (can this be overrided in the plugin I wonder?)

**Comment by Andre601** [comment]
I don't think you can override the output of `/version <plugin>` for a specific plugin alone... Or it is possible and I don't know about it.
The only thing I do know is, that the server just returns the information within the plugin's plugin.yml file, so you would need to override the command in some way to return the full info when using `/version Train_Carts`

**Comment by bergerkiller** [comment]
Looks like the only way is to store the build number in the plugin description, or perhaps at runtime modify the version String in the plugin description object. But that is probably a bad idea.

https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/command/defaults/VersionCommand.java#L70

Description might be an idea, but then people do have to post the description in the issue ticket, so meh. For now /train version is fine.

**Comment by Andre601** [comment]
The plugin uses Maven.
Wouldn't it be somehow possible to setup a system, where you would have `${project.version}` in the plugin.yml's version section and replace it with the version and build number (if available)?

I myself have a function/class which either returns the main version (`#.#.#`) or the version with build number, if the env has a matching property (`#.#.#_###`).

https://github.com/botblock/JavaBotBlockAPI/blob/468a2a47258d6151d05fbd38ccf4509b9892d34e/build.gradle#L139-L150

I do use gradle but I'm quite sure you could implement this somehow into maven's pom.xml to create a dynamic version that would include a build number.
But the question here would be, if it is worth the work to do so and how much work it would be in the first place.

**Comment by bergerkiller** [comment]
Fun fact: this is already the case. https://github.com/bergerhealer/TrainCarts/blob/master/src/main/java/plugin.yml#L5

That's how /train version gets the version number.

**Comment by weeryan17** [comment]
> I personally see absolutely no benefit of having a dedicated command that pre-fills a issue with info, since the templates do exist for valid reasons and this would only make it much more annoying.
> 
> I suggest to - at most - update the command to just provide the link to the bug report template and perhaps also mention the required info (plugin and server version) for them to fill in.

Filling out all the info in one command is a lot easier then having to run two separate commands and alt tab back and forth to fill everything out. especially cause minecraft doesn't allow copying from chat directly from the client. Yes you can copy it from the logs/console but most people don't have the console open, or know how to access the logs. However to maintain consistency it should probably request the template from github.

**Comment by Andre601** [comment]
> especially cause minecraft doesn't allow copying from chat directly from the client. Yes you can copy it from the logs/console but most people don't have the console open, or know how to access the logs. However to maintain consistency it should probably request the template from github.

That is partially incorrect.
1.15 introduced a "copy" option to JSON text which would allow you to copy a specific text into your clipboard.

**Comment by weeryan17** [comment]
Yet the version command doesn't use that system, it just sends a message. And people run traincarts on a lot more then minecraft 1.15

**Comment by bbayu123** [comment]
You also need to understand, not everyone uses 1.15 or above.

**Comment by Andre601** [comment]
The alternative would be to have the suggest command to paste the info into the chat bar to then copy it from there...

Should I look into also updating the issue command to like use a template instead?

I could try making it auto-fill info (which imo would generate a freaking long URL) or just let it display something like this:
> Click here to report an issue with TrainCarts: https://github.com/bergerhealer/TrainCarts/issues/new?template=bug_report.md
>
> Make sure to provide the following information:
> - BkCommonLib: [version]
> - TrainCarts: [version]
> - Server: [version]

Looking at how the current system just prints the url (Which is extremely ugly) would I suggest adding what I suggested now.

**Comment by weeryan17** [comment]
Again its hard to copy from minecraft so auto fill is the best solution there is. If we have the features that would let users copy from the game on ALL versions past 1.8, sure we could just link them to the bug report template, but again thats harder for the users. As for the long url issue, I could potentially make a url shortener on the traincarts website for it to interact with, but then that needs to wait on the website.

**Comment by Andre601** [comment]
I could quickly make one myself with Java, Spark and some time.
That way could you f.e. have https://traincarts.net/issue?tc=[version]&bk=[version]&server=[version] and it would redirect.
But the issue would persist where you would have an awefully long url, just to have a prefilled template with the required info.
In all honesty, having this is nothing more than cater towards lazy asses (There isn't any better word for them) who can't be bothered to spend a minute of their life to provide the requested info.

**Comment by weeryan17** [comment]
No its to cater towords the typical user who if we don't prompt then to, and if we don't make it easy to use will use the file name without the build number, or post a screenshot of the output.

**Comment by Andre601** [comment]
When we add JSON would I suggest to perhaps use JSONMessage.
I use this class here in one of my plugins and from what I know does it work cross-version.

https://github.com/Andre601/StatusNPC/blob/master/src/main/java/com/andre601/statusnpc/util/JSONMessage.java

**Comment by bergerkiller** [comment]
I have ChatText (and IChatComponent handles) for interfacing, so I could port some stuff in there to widen support. Currently all it does is offer a 'to json' and 'from json' function, so there's possibly room for improvement.

**Comment by Andre601** [comment]
> I have ChatText (and IChatComponent handles) for interfacing, so I could port some stuff in there to widen support. Currently all it does is offer a 'to json' and 'from json' function, so there's possibly room for improvement.

This would indeed be a nice idea to expand this class a bit.

**Comment by bergerkiller** [comment]
I'll merge these changes as they look good to me, perhaps a separate issue ticket can be made (feature request) for sending chat messages with custom link text. But that would likely require an API in BKCommonLib, out of scope of this PR.

**Comment by Andre601** [comment]
I'll open one on the BKCommonLib repo then.

**Pull request merged**
